### ISSUE TITLE
Undefined method Civi\Aws\CiviApi::try

### ISSUE THREAD

**Issue by mattwire** [mecachisenros/aws#3]
The method is undefined and doesn't appear to exist in the code: https://github.com/mecachisenros/aws/blob/master/CRM/Aws/Ses/Form/Identity.php#L205

**Comment by mecachisenros** [comment]
🤦‍♂ I must have missed that refactoring... I'll fix it.

**Comment by mecachisenros** [comment]
@mattwire should be fixed via 67ba978beb9be343a085150e17fd2c2c7f46fb90
